GET http://localhost:3000/me

###
GET http://localhost:3000/heroes

###
POST http://localhost:3000/heroes
Content-Type: application/json

{
	"id": "69",
	"name": "Batman",
	"powerstats": {
		"intelligence": "81",
		"strength": "40",
		"speed": "29",
		"durability": "55",
		"power": "63",
		"combat": "90"
	},
	"biography": {
		"full-name": "Terry McGinnis",
		"alter-egos": "No alter egos found.",
		"aliases": ["The Tomorrow Knight"],
		"place-of-birth": "Gotham City, 25th Century",
		"first-appearance": "Batman Beyond #1",
		"publisher": "DC Comics",
		"alignment": "good"
	}
}

###
GET http://localhost:3000/heroes/60e470b58c4e6738881933b1

###
GET http://localhost:3000/heroes/bio/60e470b58c4e6738881933b1

###
DELETE http://localhost:3000/heroes/60e470b58c4e6738881933b1

###
PATCH http://localhost:3000/heroes/60e5a25e564df64abfed649b
Content-Type: application/json

{
  "biography":{
    "full-name": "Bruce Wayne"
  }
}

###
GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "email":"email@email.com",
    "password":"password",
    "role":"user"
  
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/60e5b42c1e2c25510be54c17

###
PATCH http://localhost:3000/users/60e5c001f065a7564372778c
Content-Type: application/json

{
  "email":"jeanjean@gmail.com"
}


###
DELETE http://localhost:3000/users/60e5c001f065a7564372778c

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email":"email@email.com",
  "password": "password"
}

###
GET http://localhost:3000/protected
Authorization: Bearer argon2i$v=19$m=4096,t=3,p=1$PQpFAWLEnjt5N9CW+d49WQ$suGnwVIpfvl0cENXwzTxwjvIhY6VwsxiEPRqOBaGsWU